/**
 * Static country lookup tables shared across the codebase.
 * Centralised here to keep compare.js focused on logic.
 */

// Known country name aliases — maps provider-specific names to canonical display name
const COUNTRY_ALIASES = {
  'usa': 'United States',
  'united states of america': 'United States',
  'arab emirates': 'United Arab Emirates',
  'uae': 'United Arab Emirates',
  'uk': 'United Kingdom',
  'great britain': 'United Kingdom',
  'macau': 'Macao',
  'east timor': 'Timor-Leste',
  'timor - leste': 'Timor-Leste',
  'democratic republic of congo': 'Democratic Republic of the Congo',
  'democratic republic of the congo': 'Democratic Republic of the Congo',
  'drc': 'Democratic Republic of the Congo',
  'republic of the congo': 'Republic of Congo',
  'north macedonia': 'North Macedonia',
  'macedonia': 'North Macedonia',
  'cote d ivoire': "Côte d'Ivoire",
  "cote d'ivoire": "Côte d'Ivoire",
  'ivory coast': "Côte d'Ivoire",
  'sint maarten': 'Sint Maarten (Dutch Part)',
  'us virgin islands': 'Virgin Islands (U.S.)',
  'faroe': 'Faroe Islands',
  'faeroe islands': 'Faroe Islands',
  'us vi': 'Virgin Islands (U.S.)',
  'caribbean cruise': 'Caribbean (Multi-country)',
  'alaska cruise': 'Alaska Cruise',
  'europe cruise': 'Europe (Multi-country)',
  'mediterranean cruise': 'Mediterranean Cruise',
  'latin america': 'Latin America',
  'latin america and caribbean': 'Latin America',
  'americas': 'Americas',
  // Fix split rows
  'palestine, state of': 'Palestine',
  'guinea bissau': 'Guinea-Bissau',
  'saint barthelemy': 'Saint Barthélemy',
  'saint vincent and grenadines': 'Saint Vincent and the Grenadines',
  'u.s. virgin islands': 'Virgin Islands (U.S.)',
  'curacao': 'Curaçao',
  'reunion': 'Réunion',
  'bonaire, sint eustatius and saba': 'Bonaire',
  'saint martin (french part)': 'Saint Martin',
  // Extra common variants
  'antigua and barbuda': 'Antigua and Barbuda',
  'trinidad and tobago': 'Trinidad and Tobago',
  'south georgia': 'South Georgia and the South Sandwich Islands',
};

// ISO-2 overrides for countries where no provider supplies a 2-letter code.
// Keyed on canonical display name (lowercase).
const COUNTRY_ISO2 = {
  // Standard ISO-2 missing from provider raw data
  'belarus': 'BY',
  'bhutan': 'BT',
  'lebanon': 'LB',
  'vatican city': 'VA',
  'ethiopia': 'ET',
  'palestine': 'PS',
  'virgin islands (u.s.)': 'VI',
  'bonaire': 'BQ',
  'réunion': 'RE',
  'saint barthélemy': 'BL',
  'saint martin': 'MF',
  'guinea-bissau': 'GW',
  'saint vincent and the grenadines': 'VC',
  'antigua and barbuda': 'AG',
  'turks and caicos islands': 'TC',
  'trinidad and tobago': 'TT',
  'faroe islands': 'FO',
  'macao': 'MO',
  'timor-leste': 'TL',
  'north macedonia': 'MK',
  'curaçao': 'CW',
  'sint maarten (dutch part)': 'SX',
  "côte d'ivoire": 'CI',
  'democratic republic of the congo': 'CD',
  'republic of congo': 'CG',
  // Territories — use parent country flag
  'azores': 'PT',
  'madeira': 'PT',
  'canary islands': 'ES',
  'marie-galante': 'FR',
  'scotland': 'GB',
  'northern cyprus': 'CY',
  'saba': 'BQ',
  'sint eustatius': 'BQ',
  'netherlands antilles': 'AN',
  // Regional bundles — use EU/globe pseudo-codes handled by flagEmoji()
  'europe': 'EU',
  'eastern europe': 'EU',
  'scandinavia': 'EU',
  'balkans': 'EU',
  'middle east and north africa': '__GLOBE__',
  'asia': '__GLOBE__',
  'oceania 1': '__GLOBE__',
  'oceania': '__GLOBE__',
  'global': '__GLOBE__',
  'north america': '__GLOBE__',
  'latin america': '__GLOBE__',
  'central america': '__GLOBE__',
  'caribbean': '__GLOBE__',
  'caribbean (multi-country)': '__GLOBE__',
  'africa 1': '__GLOBE__',
  'africa 2': '__GLOBE__',
  'africa': '__GLOBE__',
  'africa safari': '__GLOBE__',
  'asia and oceania': '__GLOBE__',
  'caribbean islands': '__GLOBE__',
  'middle east': '__GLOBE__',
  'european union and united kingdom': 'EU',
  'eu plus uk': 'EU',
  'southeast asia': '__GLOBE__',
  'china hong kong macau': 'CN',
  'japan china': 'JP',
  'japan south korea': 'JP',
};

module.exports = { COUNTRY_ALIASES, COUNTRY_ISO2 };
